### ISSUE TITLE
Angular Django Tutorial

### ISSUE THREAD

**Issue by milapbhojak** [econchick/new-coder#139]
How about adding Angular Django tutorial? I can help you in that.

**Comment by econchick** [comment]
Hey @milapbhojak -

The new coder tutorials are just Python-based (my language of choice). A Django tutorial would definitely fit, but I'm unsure of the Angular part.  Partly because I'm not a JS dev, and partly because it's outside the scope of the site.

If you'd like to write up a complete Angular + Django tutorial, please feel free!  I'll create a separate portion of the site that points to equally awesome tutorials.
