### ISSUE TITLE
wrong XPATHs Scrape tutorial

### ISSUE THREAD

**Issue by caynan** [econchick/new-coder#140]
All the XPATHs on ```livingsocial_spider.py``` is wrong. So because of that the scrapy doesn't generate any data.

**Comment by econchick** [comment]
@caynan - wrt iPython notebooks - yes! during the long holiday weekend in two weeks, I have plans to "hack" all weekend on new coder (finally).  If you'd like to participate with me - like via IRC or something - let me know! even if it's for a few hours.  @merwok you interested at all?

**Comment by caynan** [comment]
@econchick sounds like a plan for me :smile: I'm caynan on freenode, just ping me.

**Comment by econchick** [comment]
Hey @caynan.  A couple of things:

1. I took your PR code and adapted it in - thank you so much!  I also made a couple of changes (e.g. since there's no `category` of deals, I just removed it entirely, as well as added `orig_price` field and `end_date` field).
2. About the iPython NB - I've decided that I want to create IPyNBs for all the tutorials (tutorial language & code) for the "Workshop Kit" portion of the site (newcoder.io/workshop).  I am going to create a separate issue for that describing more in detail.  If you want, you can assign it to yourself (the whole issue, or particular tutorials).

I'll push a site & code update a little bit later.  Thanks!

**Comment by caynan** [comment]
Hey @econchick 

I'd love to help with the IPyNB migration, should I just create a notebook containing the text and the codes as already in the tutorials? 
Or should we try to do something like leaving cells blank for the user to fulfill?

:smile:
